/* Automatically generated by po2tbl.sed from genius.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"GnomENIUS Calculator", 2},
  {"The Gnome Calculator program", 3},
  {"GnomENIUS Calculator setup", 4},
  {"General", 5},
  {"Properties", 6},
  {"Prefix notation", 7},
  {"Infix notation", 8},
  {"Postfix notation (RPN)", 9},
  {"Full (exact) answers", 10},
  {"Make floats integers (e.g. 10.0=10)", 11},
  {"Results as floats", 12},
  {"Floats in scientific notation", 13},
  {"Properties...", 14},
  {"Exit", 15},
  {"Numpad", 16},
  {"Scientific", 17},
  {"About...", 18},
  {"Calculator", 19},
  {"View", 20},
  {"Help", 21},
  {"Display", 22},
  {"The Gnome calculator style edition of genius", 23},
  {"Variable used uninitialized!", 24},
  {"Left value is NOT a number! (ignoring if construct)", 25},
  {"Left value is NOT a number! (ignoring ifelse construct)", 26},
  {"'=' can't function without proper nodes!", 27},
  {"Left value is NOT a 0\\function! (ignoring '=')", 28},
  {"Right value is NOT computed! (ignoring '=')", 29},
  {"funcdefop can't function without proper nodes!", 30},
  {"Left value is NOT a function! (ignoring function definition)", 31},
  {"ERROR: Probably corrupt stack!", 32},
  {"ERROR: ", 33},
  {" before '", 34},
  {"Stack underflow!", 35},
};

int _msg_tbl_length = 35;
