/* Automatically generated by po2tbl.sed from genius.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Error", 2},
  {"Information", 3},
  {"\
\n\
Too many errors! (%d followed)", 4},
  {"\\e[01;31mToo many errors! (%d followed)\\e[0m\n", 5},
  {"GnomENIUS Calculator", 6},
  {"The Gnome calculator style edition of genius", 7},
  {"GnomENIUS Calculator setup", 8},
  {"Output", 9},
  {"Number/Expression output options", 10},
  {"Maximum digits to output (0=unlimited)", 11},
  {"Results as floats", 12},
  {"Floats in scientific notation", 13},
  {"Always print full expressions", 14},
  {"Error/Info output options", 15},
  {"Display errors in a dialog", 16},
  {"Display information messages in a dialog", 17},
  {"Maximum errors to display (0=unlimited)", 18},
  {"Precision", 19},
  {"Floating point precision", 20},
  {"\
NOTE: The floating point precision might not take effect\n\
for all numbers immediately, only new numbers calculated\n\
and new variables will be affected.", 21},
  {"Floating point precision (bits)", 22},
  {"Terminal", 23},
  {"Terminal options", 24},
  {"Scrollback lines", 25},
  {"Font:", 26},
  {"Can not open file!", 27},
  {"Load GEL file", 28},
  {"_Load", 29},
  {"Load and execute a file in genius", 30},
  {"_Interrupt", 31},
  {"Interrupt current calculation", 32},
  {"_Calculator", 33},
  {"_Plugins", 34},
  {"Interrupt", 35},
  {"\
Genius %s\n\
Copyright (c) 1997,1998,1999 Free Software Foundation, Inc.\n\
This is free software with ABSOLUTELY NO WARRANTY.\n\
For details type `warranty'.\n\
\n", 36},
  {"Wrong argument type as matrix index", 37},
  {"Matrix index too large", 38},
  {"Matrix index less then 1", 39},
  {"Matrix 'to' index less then 'from' index", 40},
  {"Indexed Lvalue not user function", 41},
  {"Dereference of non-identifier!", 42},
  {"Dereference of undefined variable!", 43},
  {"Dereference of non-reference!", 44},
  {"Indexed Lvalue not an identifier or a dereference", 45},
  {"Lvalue not an identifier/dereference/matrix location!", 46},
  {"Referencing an undefined variable!", 47},
  {"Can't set a region to a region of a different size", 48},
  {"Function '%s' used unintialized", 49},
  {"Variable '%s' used unintialized", 50},
  {"Can't dereference '%s'!", 51},
  {"Can't call a non-function!", 52},
  {"\
Call of '%s' with the wrong number of arguments!\n\
(should be %d)", 53},
  {"Extraneous return value!", 54},
  {"Reference function with arguments encountered!", 55},
  {"Unnamed reference function encountered!", 56},
  {"Unevaluatable function type encountered!", 57},
  {"Trying to dereference '%s' which is not a reference!\n", 58},
  {"NULL reference encountered!", 59},
  {"Unnamed reference function encountered", 60},
  {"Variable '%s' used unitialized", 61},
  {"Bad type for 'for' loop!", 62},
  {"'for' loop increment can't be 0", 63},
  {"Logical and can only operate on numeric/string data", 64},
  {"Cannot compare non value-only matrixes", 65},
  {"Primitives must get numeric/matrix/string arguments", 66},
  {"Can't add/subtract two matricies of different sizes", 67},
  {"Can't multiply matricies of wrong sizes", 68},
  {"Powers are defined on (square matrix)^(integer) only", 69},
  {"Matrix appears singular and can't be inverted", 70},
  {"Can't divide matrices of different sizes or non-square matrices", 71},
  {"In backdivision matrix dimensions must agree", 72},
  {"Can't divide by a non-square matrix", 73},
  {"Can't operate on a non value-only matrix", 74},
  {"Can't transpose non-matrix", 75},
  {"Index works only on matricies", 76},
  {"Matrix index out of range", 77},
  {"Index out of range", 78},
  {"Can't evaluate return value!", 79},
  {"Called 'continue' outside of a loop", 80},
  {"Called 'break' outside of a loop", 81},
  {"Can't do mod by non-numbers!", 82},
  {"Can't do mod calculations of non-integers!", 83},
  {"Unexpected operator!", 84},
  {"Cannot compare matrixes", 85},
  {"Unexpected node!", 86},
  {"Could not evaluate predicate into a numeric boolean value!", 87},
  {"Bad identifier for function node!", 88},
  {"NULL tree!", 89},
  {"NULL function!", 90},
  {"Unexpected function type!", 91},
  {"File '%s' is a wrong version of GEL", 92},
  {"Badly formed record", 93},
  {"Record out of place", 94},
  {"Missing value for function", 95},
  {"Can't open file: '%s'", 96},
  {"Cannot open plugin '%s'!", 97},
  {"ERROR: Probably corrupt stack!", 98},
  {"ERROR: Can't execute more things at once!", 99},
  {"ERROR: ", 100},
  {" before newline", 101},
  {" at end of input", 102},
  {" before '", 103},
  {"Stack underflow!", 104},
  {"Number too large to compute exponential!", 105},
  {"Can't do modulo of floats or rationals!", 106},
  {"Can't do GCD of floats or rationals!", 107},
  {"Can't get jacobi symbols of floats or rationals!", 108},
  {"Can't get legendre symbols of floats or rationals!", 109},
  {"perfect_square: can't work on non-integers!", 110},
  {"Can't do factorials of rationals or floats!", 111},
  {"Number too large to compute factorial!", 112},
  {"Can't do factorials of negative numbers!", 113},
  {"0^0 is undefined", 114},
  {"Can't compare complex numbers", 115},
  {"Division by zero!", 116},
  {"Can't modulo complex numbers", 117},
  {"Can't GCD complex numbers", 118},
  {"Can't get jacobi symbols of complex numbers", 119},
  {"Can't get legendre symbols complex numbers", 120},
  {"perfect_square: can't work on complex numbers", 121},
  {"ln: can't take logarithm of 0", 122},
  {"Can't make factorials of complex numbers", 123},
  {"Can't determine type of a complex number", 124},
  {"Can't convert complex number into integer", 125},
  {"Can't convert real number to integer", 126},
  {"Integer too large for this operation", 127},
  {"line %d: %s\n", 128},
  {"Too many errors! (%d followed)\n", 129},
  {"\
Genius %s usage:\n\
\n\
genius [options] [files]\n\
\n\
\t--precision=num   \tFloating point precision [256]\n\
\t--maxdigits=num   \tMaximum digits to display (0=no limit) [0]\n\
\t--[no]floatresult \tAll results as floats [OFF]\n\
\t--[no]scinot      \tResults in scientific notation [OFF]\n\
\t--[no]fullexp     \tAlways print full expressions [OFF]\n\
\t--maxerrors=num   \tMaximum errors to display (0=no limit) [5]\n\
\t--[no]readline    \tUse readline if it is available [ON]\n\
\t--[no]compile     \tCompile everything and dump it to stdout [OFF]\n\
\t--[no]quiet       \tBe quiet during non-interactive mode,\n\
\t                  \t(always on when compiling) [OFF]\n\
\n", 130},
  {"Can't open file", 131},
  {"Determinant of a non-square matrix is undefined", 132},
  {"Bad tree record when decompiling", 133},
};

int _msg_tbl_length = 133;
