/* Automatically generated by po2tbl.sed from genius.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"GnomENIUS Calculator", 2},
  {"The Gnome calculator style edition of genius", 3},
  {"GnomENIUS Calculator setup", 4},
  {"General", 5},
  {"Properties", 6},
  {"Full (exact) answers", 7},
  {"Make floats integers (e.g. 10.0=10)", 8},
  {"Results as floats", 9},
  {"Floats in scientific notation", 10},
  {"_Properties...", 11},
  {"E_xit", 12},
  {"_Numpad", 13},
  {"_Scientific", 14},
  {"_About...", 15},
  {"_Calculator", 16},
  {"_View", 17},
  {"_Help", 18},
  {"Display", 19},
  {"Numpad", 20},
  {"Scientific", 21},
  {"Lvalue not an identifier/dereference!", 22},
  {"Variable '%s' used unintialized", 23},
  {"Dereference of non-identifier!", 24},
  {"Dereference of non-reference!", 25},
  {"Function '%s' used unintialized", 26},
  {"Can't dereference '%s'!", 27},
  {"Can't call a non-function!", 28},
  {"\
Call of '%s' with the wrong number of arguments!\n\
(should be %d)", 29},
  {"Extraneous return value!", 30},
  {"Reference function with arguments encountered!", 31},
  {"Unnamed reference function encountered!", 32},
  {"Unevaluatable function type encountered!", 33},
  {"Trying to dereference '%s' which is not a reference!\n", 34},
  {"NULL reference encountered!", 35},
  {"Unnamed reference function encountered", 36},
  {"Variable '%s' used unitialized", 37},
  {"Logical not only define on numbers", 38},
  {"Unexpected operator!", 39},
  {"Unexpected node!", 40},
  {"Could not evaluate predicate into a numeric boolean value!", 41},
  {"Bad identifier for function node!", 42},
  {"NULL tree!", 43},
  {"NULL function!", 44},
  {"Unexpected function type!", 45},
  {"ERROR: Probably corrupt stack!", 46},
  {"ERROR: ", 47},
  {" before '", 48},
  {"Stack underflow!", 49},
};

int _msg_tbl_length = 49;
