/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 58
#define YY_END_OF_BUFFER 59
static yyconst short int yy_acclist[172] =
    {   0,
       59,   57,   58,   53,   57,   58,   52,   58,   54,   57,
       58,   57,   58,   55,   57,   58,   24,   57,   58,   25,
       57,   58,   56,   57,   58,   50,   57,   58,   50,   57,
       58,   50,   57,   58,   50,   57,   58,    5,   57,   58,
       12,   57,   58,   14,   57,   58,   13,   57,   58,   28,
       57,   58,   57,   58,   28,   57,   58,   28,   57,   58,
       28,   57,   58,   28,   57,   58,   28,   57,   58,   28,
       57,   58,   28,   57,   58,   22,   57,   58,   23,   57,
       58,    6,   57,   58,   55,   57,   58,   53,    8,    1,
       42,   49,   50,   50,   35,   50,   10,    7,   11,   28,

       51,   28,   28,   21,   28,   28,   28,   18,   28,   28,
       28,   28,   28,   47,   47,   47,   36,   41,   27,   48,
        9,   16,   28,   28,   28,   28,   15,   28,   28,   28,
       28,   17,   28,   39,   46,   47,   47,   31,   40,   34,
       27,   44,   26,   28,   28,   28,   28,   28,   28,   32,
       38,   45,   33,   28,    2,   28,   28,   28,   19,   28,
       37,   30,   43,   20,   28,   28,    3,   28,   29,    4,
       28
    } ;

static yyconst short int yy_accept[127] =
    {   0,
        1,    1,    1,    1,    1,    2,    4,    7,    9,   12,
       14,   17,   20,   23,   26,   29,   32,   35,   38,   41,
       44,   47,   50,   53,   55,   58,   61,   64,   67,   70,
       73,   76,   79,   82,   85,   88,   89,   90,   90,   91,
       92,   92,   94,   95,   95,   95,   96,   96,   96,   97,
       98,   99,  100,  101,  102,  103,  104,  106,  107,  108,
      110,  111,  112,  113,  114,  114,  115,  116,  117,  117,
      118,  118,  119,  120,  121,  121,  122,  124,  125,  126,
      127,  129,  130,  131,  132,  134,  135,  137,  138,  138,
      139,  139,  139,  139,  140,  141,  142,  143,  145,  146,

      147,  148,  149,  150,  150,  151,  151,  152,  153,  153,
      154,  155,  157,  158,  159,  161,  161,  162,  163,  164,
      166,  167,  169,  170,  172,  172
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    5,    1,    6,    1,    1,    7,
        8,    6,    6,    1,    9,   10,    6,   11,   12,   12,
       12,   13,   13,   13,   13,   14,   15,    1,   16,   17,
       18,   19,    1,   20,   21,   21,   21,   21,   21,   21,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
        7,   23,    8,    6,    1,    1,   24,   21,   21,   25,

       26,   27,   28,   29,   30,   22,   22,   31,   22,   32,
       33,   34,   22,   35,   36,   37,   22,   22,   38,   39,
       22,   22,   40,    1,   41,   42,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[43] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        2,    2,    2,    2,    2,    1,    1,    1,    1,    3,
        4,    5,    1,    4,    4,    6,    4,    5,    5,    7,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    1,
        1,    1
    } ;

static yyconst short int yy_base[136] =
    {   0,
        0,    0,  238,  237,  245,  310,  242,  310,  225,  238,
      310,  310,  310,   32,   38,   73,   58,  217,  310,  221,
      220,  203,    0,  217,   22,   28,  176,  166,   30,  171,
      156,  310,  310,  310,   94,  179,  310,  177,  310,   36,
       99,   36,   69,  106,    0,  310,    0,    0,  156,  152,
      310,  310,    0,  310,  145,  141,  142,  134,  123,    0,
      123,  132,  125,  119,  111,  117,  152,  127,  137,  310,
      162,  172,    0,    0,  148,  310,    0,   67,  114,  114,
        0,   99,  108,  103,    0,   71,   94,  111,  179,  310,
        0,    0,  184,  192,  310,    0,  310,    0,   66,   61,

       71,   65,   68,  199,  310,  204,  212,    0,   85,  310,
       63,    0,   52,   37,    0,  217,  222,  310,  310,    0,
       28,    0,  310,    0,  310,  252,  258,  264,  268,  274,
      279,  285,  291,  297,  302
    } ;

static yyconst short int yy_def[136] =
    {   0,
      125,    1,    1,    1,  125,  125,  125,  125,  125,  126,
      125,  125,  125,  125,  125,  125,   16,   17,  125,  125,
      125,  125,  127,  125,  127,  127,  127,  127,  127,  127,
      127,  125,  125,  125,  125,  125,  125,  126,  125,  128,
      125,   15,   17,  125,  129,  125,  130,  131,   17,  125,
      125,  125,  127,  125,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  125,  125,  125,   67,  125,  125,
      125,  125,  132,  130,  131,  125,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  133,   66,   68,  125,  125,
      134,  135,  125,  125,  125,  132,  125,  127,  127,  127,

      127,  127,  127,  125,  125,  125,  125,  134,  135,  125,
      127,  127,  127,  127,  127,  125,  125,  125,  125,  127,
      127,  127,  125,  127,    0,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125
    } ;

static yyconst short int yy_nxt[353] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   11,   14,
       15,   16,   17,   17,   18,   19,   20,   21,   22,   11,
       23,   23,   24,   25,   23,   23,   23,   23,   23,   26,
       23,   27,   28,   29,   23,   23,   23,   30,   31,   32,
       33,   34,   40,   40,   40,   40,   40,   41,   42,   42,
       42,   43,   43,   55,   57,   69,   56,   44,  125,   58,
       45,   69,   61,   44,   62,   70,  124,   46,   43,   43,
       43,   43,   43,  125,  125,  122,   47,   48,   98,   98,
       98,  121,   41,   49,   49,   49,   49,   49,  120,  119,
      104,  125,   44,  115,  114,   45,  104,  113,   44,  112,

      105,  111,   46,   65,   66,   67,   68,   68,   68,   40,
       40,   40,   40,   40,   71,  125,   72,   72,   72,   72,
       72,   86,   86,   86,   86,   86,   65,   87,   87,   87,
       88,   88,  125,  103,  102,  101,   89,   88,   88,   88,
       88,   88,   89,  100,   99,   93,   90,   94,   94,   94,
       94,   94,   97,   85,   84,   91,   92,   83,   82,   81,
       80,   65,   68,   68,   68,   68,   68,   79,   78,   77,
       76,   89,   72,   72,   72,   72,   72,   89,  125,   39,
       36,   90,   72,   72,   72,   72,   72,  106,   64,  107,
      107,  107,  107,  107,   94,   94,   94,   94,   94,   63,

       60,   95,   94,   94,   94,   94,   94,  116,   59,  117,
      117,  117,  117,  117,  107,  107,  107,  107,  107,   54,
       52,  110,  107,  107,  107,  107,  107,  117,  117,  117,
      117,  117,  117,  117,  117,  117,  117,   51,   50,  125,
       39,  118,   37,   36,  125,   35,   35,  125,  125,  125,
      125,  123,   38,   38,   38,   38,   38,   38,   38,   53,
      125,   53,   53,   53,   53,   40,   40,  125,  125,   40,
       40,   73,   73,   73,   73,   74,  125,   74,  125,   74,
       75,  125,   75,   75,   75,   75,   96,  125,   96,   96,
       96,   96,   86,   86,  125,  125,   86,   86,  108,  125,

      108,  125,  108,  109,  125,  109,  109,  109,  109,    5,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125
    } ;

static yyconst short int yy_chk[353] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,   14,   14,   14,   14,   14,   15,   15,   15,
       15,   15,   15,   25,   26,   40,   25,   15,   42,   26,
       15,   40,   29,   15,   29,   40,  121,   15,   17,   17,
       17,   17,   17,   43,   42,  114,   15,   16,   78,   78,
       78,  113,   16,   16,   16,   16,   16,   16,  111,  109,
       86,   43,   16,  103,  102,   16,   86,  101,   16,  100,

       86,   99,   16,   35,   35,   35,   35,   35,   35,   41,
       41,   41,   41,   41,   44,   88,   44,   44,   44,   44,
       44,   65,   65,   65,   65,   65,   66,   66,   66,   66,
       66,   66,   87,   84,   83,   82,   66,   68,   68,   68,
       68,   68,   66,   80,   79,   69,   66,   69,   69,   69,
       69,   69,   75,   64,   63,   66,   67,   62,   61,   59,
       58,   67,   67,   67,   67,   67,   67,   57,   56,   55,
       50,   67,   71,   71,   71,   71,   71,   67,   49,   38,
       36,   67,   72,   72,   72,   72,   72,   89,   31,   89,
       89,   89,   89,   89,   93,   93,   93,   93,   93,   30,

       28,   72,   94,   94,   94,   94,   94,  104,   27,  104,
      104,  104,  104,  104,  106,  106,  106,  106,  106,   24,
       22,   94,  107,  107,  107,  107,  107,  116,  116,  116,
      116,  116,  117,  117,  117,  117,  117,   21,   20,   18,
       10,  107,    9,    7,    5,    4,    3,    0,    0,    0,
        0,  117,  126,  126,  126,  126,  126,  126,  126,  127,
        0,  127,  127,  127,  127,  128,  128,    0,    0,  128,
      128,  129,  129,  129,  129,  130,    0,  130,    0,  130,
      131,    0,  131,  131,  131,  131,  132,    0,  132,  132,
      132,  132,  133,  133,    0,    0,  133,  133,  134,    0,

      134,    0,  134,  135,    0,  135,  135,  135,  135,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#define INITIAL 0
/* GnomENIUS Calculator
 * Copyright (C) 1997, 1998 the Free Software Foundation.
 *
 * Author: George Lebl
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the  Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307,
 * USA.
 */
#line 22 "lexer.l"
#include <glib.h>
#include <string.h>
#include "mpwrap.h"
#include "eval.h"
#include "dict.h"
#include "calc.h"
#include "parse.h"
#ifdef WITH_READLINE_SUPPORT
#include <readline/readline.h>
#endif

int lex_fd[2];
int first_tok = INFIX_EXPR;
int return_ret = FALSE;
static int block_depth = 0;
static int parenth_depth = 0;
GList *notation_stack = NULL;
int use_readline = FALSE;
int lex_init = TRUE;
extern evalstack_t evalstack;

void push_notation(notation_t not);
void pop_notation(void);

#define LEX_NOTATION (GPOINTER_TO_INT(notation_stack->data))

#define NO_RET {return_ret = FALSE;}
#define DO_RET { \
	if(!block_depth && !parenth_depth) \
		return_ret = TRUE; \
	else \
		return_ret = FALSE; \
}

#define FUNC_RET { \
	if(LEX_NOTATION==POSTFIX_NOTATION) { \
		DO_RET; \
	} else { \
		NO_RET; \
	} \
}

#ifdef WITH_READLINE_SUPPORT
#define NEXT_LINE {							\
	while(use_readline) {						\
		char *s = readline(!evalstack?"genius> ":"> ");		\
		if(!s)							\
			return EOF;					\
		if(!*s)							\
			continue;					\
		add_history(s);						\
									\
		/*this seems ugly but for some reason that's the only	\
		  way it works*/					\
		close(lex_fd[0]);					\
									\
		pipe(lex_fd);						\
		yyin=fdopen(lex_fd[0],"r");				\
									\
		write(lex_fd[1],s,strlen(s));				\
		write(lex_fd[1],"\n",1);				\
		close(lex_fd[1]);					\
		break;							\
	}								\
}
#else
#define NEXT_LINE ;
#endif

#define NEGATIVE 1

#line 604 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 95 "lexer.l"



	if(lex_init) {
		return_ret = FALSE;
		block_depth = 0;
		parenth_depth = 0;
		lex_init = FALSE;
	}
	
	if(first_tok!=INT_MAX) {
		int i = first_tok;
		first_tok = INT_MAX;
		if(i==INFIX_EXPR) {
			BEGIN INITIAL;
		} else {
			BEGIN NEGATIVE;
		}
		return i;
	}


#line 778 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 126 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 310 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 117 "lexer.l"
; /*comment, ignore*/
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 119 "lexer.l"
{
			NO_RET;
			push_notation(INFIX_NOTATION);
			return INLINE_INFIX;
		}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 124 "lexer.l"
{
			NO_RET;
			push_notation(PREFIX_NOTATION);
			return INLINE_PREFIX;
		}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 129 "lexer.l"
{
			NO_RET;
			push_notation(POSTFIX_NOTATION);
			return INLINE_POSTFIX;
		}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 135 "lexer.l"
{ NO_RET; return SEPAR; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 137 "lexer.l"
{ NO_RET; return NEG; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 139 "lexer.l"
{ NO_RET; return EQ_CMP; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 140 "lexer.l"
{ NO_RET; return NE_CMP; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 141 "lexer.l"
{ NO_RET; return CMP_CMP; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 143 "lexer.l"
{ NO_RET; return LE_CMP; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 144 "lexer.l"
{ NO_RET; return GE_CMP; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 146 "lexer.l"
{ NO_RET; return LT_CMP; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 147 "lexer.l"
{ NO_RET; return GT_CMP; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 149 "lexer.l"
{ NO_RET; return EQUALS; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 151 "lexer.l"
{ NO_RET; return LOGICAL_NOT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 152 "lexer.l"
{ NO_RET; return LOGICAL_AND; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 153 "lexer.l"
{ NO_RET; return LOGICAL_XOR; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 154 "lexer.l"
{ NO_RET; return LOGICAL_OR; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 156 "lexer.l"
{ NO_RET; return WHILE_CONS; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 158 "lexer.l"
{ NO_RET; return IFELSE_CONS; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 160 "lexer.l"
{ NO_RET; return IF_CONS; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 162 "lexer.l"
{
			/*create a new context and push it on top of the
			  context stack, it's only temporary*/
			d_addcontext(NULL);
			block_depth++;
			NO_RET;
			return BEGINBLOCK;
		}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 171 "lexer.l"
{

			/*kill the temporary context, but keep the
			  declarations*/
			freedict(d_popcontext(),TRUE);
			block_depth--;
			DO_RET;
			return ENDBLOCK;
		}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 181 "lexer.l"
{
			parenth_depth++;
			NO_RET;
			return yytext[0];
		}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 187 "lexer.l"
{
			parenth_depth--;
			DO_RET;
			return yytext[0];
		}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 193 "lexer.l"
{
			DO_RET;
			/*make static argument placeholders*/
			if((yylval.func=d_lookup(yytext,FALSE))==NULL)
				yylval.func=d_addfunc(d_makeufunc(yytext,
					NULL,NULL,0,FALSE));
			return FUNCID0;
		}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 202 "lexer.l"
{
				/*this is the function declaration*/
				NO_RET;

				/*create a dummy function, first character is
				  the number of arguments*/
				yylval.func=
					d_addfunc(d_makeufunc(&yytext[2],NULL,
						NULL,(int)(yytext[0]-'0'),
						FALSE));
				return FUNCDEF;
			}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 215 "lexer.l"
{
				/* we need to find out the number of arguments
				   for this function, this is a limitation of
				   mostly the postfix and prefix notation
				   without parenthesis */
				func_t *n;

				n=d_lookup(yytext,TRUE);
				if(!n) {
					/*create a dummy function*/
					yylval.func=
						d_addfunc(d_makeufunc(
							yytext,NULL,NULL,0,
							FALSE));
					DO_RET;
					return FUNCID0;
				}

				yylval.func=n;
				switch(n->nargs) {
					case 0: DO_RET; return FUNCID0;
					case 1: FUNC_RET; return FUNCID1;
					case 2: FUNC_RET; return FUNCID2;
					case 3: FUNC_RET; return FUNCID3;
					case 4: FUNC_RET; return FUNCID4;
					case 5: FUNC_RET; return FUNCID5;
					case 6: FUNC_RET; return FUNCID6;
					case 7: FUNC_RET; return FUNCID7;
					case 8: FUNC_RET; return FUNCID8;
				}
				/*too many args or corrupted entry, this
				  shouldn't happen, and this is not a way
				  to deal with it, but oh well, for now*/
				REJECT;
			}
	YY_BREAK
case 29:
#line 252 "lexer.l"
case 30:
#line 253 "lexer.l"
case 31:
#line 254 "lexer.l"
case 32:
YY_RULE_SETUP
#line 254 "lexer.l"
{
			char *s;
			if(yytext[1] == '.')
				s = g_strconcat("-0",&yytext[1],NULL);
			else
				s = g_strdup(yytext);
			mpw_init(yylval.val);
			mpw_set_str_complex(yylval.val,s,10);
			g_free(s);
			DO_RET;
			return NEGNUM;
		}
	YY_BREAK
case 33:
#line 268 "lexer.l"
case 34:
#line 269 "lexer.l"
case 35:
#line 270 "lexer.l"
case 36:
YY_RULE_SETUP
#line 270 "lexer.l"
{
			char *s;
			if(yytext[0] == '.')
				s = g_strconcat("0",&yytext[0],NULL);
			else
				s = g_strdup(yytext);
			mpw_init(yylval.val);
			mpw_set_str_complex(yylval.val,s,10);
			g_free(s);
			DO_RET;
			return POSNUM;
		}
	YY_BREAK
case 37:
#line 284 "lexer.l"
case 38:
#line 285 "lexer.l"
case 39:
YY_RULE_SETUP
#line 285 "lexer.l"
{
			char *s;
			if(yytext[1] == '.')
				s = g_strconcat("-0",&yytext[1],NULL);
			else
				s = g_strdup(yytext);
			mpw_init(yylval.val);
			mpw_set_str_float(yylval.val,s,10);
			g_free(s);
			DO_RET;
			return NEGNUM;
		}
	YY_BREAK
case 40:
#line 299 "lexer.l"
case 41:
#line 300 "lexer.l"
case 42:
YY_RULE_SETUP
#line 300 "lexer.l"
{
			char *s;
			if(yytext[0] == '.')
				s = g_strconcat("0",&yytext[0],NULL);
			else
				s = g_strdup(yytext);
			mpw_init(yylval.val);
			mpw_set_str_float(yylval.val,s,10);
			g_free(s);
			DO_RET;
			return POSNUM;
		}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 313 "lexer.l"
{
			char *s;
			int base;

			s=g_malloc(strlen(yytext)-2); /*minus 3 and plus 1*/
			sscanf(yytext,"-%d#%[0-9a-zA-Z]s#",&base,s);
			if(base>36) { g_free(s); REJECT; }
			mpw_init(yylval.val);
			mpw_set_str_int(yylval.val,s,base);
			mpw_neg(yylval.val,yylval.val);
			DO_RET;
			return NEGNUM;
		}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 327 "lexer.l"
{
			char *s;
			int base;

			s=g_malloc(strlen(yytext)-2); /*minus 3 and plus 1*/
			sscanf(yytext,"%d#%[0-9a-zA-Z]s#",&base,s);
			if(base>36) { g_free(s); REJECT; }
			mpw_init(yylval.val);
			mpw_set_str_int(yylval.val,s,base);
			DO_RET;
			return POSNUM;
		}
	YY_BREAK
case 45:
#line 341 "lexer.l"
case 46:
#line 342 "lexer.l"
case 47:
YY_RULE_SETUP
#line 342 "lexer.l"
{
			mpw_init(yylval.val);
			mpw_set_str_int(yylval.val,yytext,0);
			DO_RET;
			return NEGNUM;
		}
	YY_BREAK
case 48:
#line 350 "lexer.l"
case 49:
#line 351 "lexer.l"
case 50:
YY_RULE_SETUP
#line 351 "lexer.l"
{
			mpw_init(yylval.val);
			mpw_set_str_int(yylval.val,yytext,0);
			DO_RET;
			return POSNUM;
		}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 358 "lexer.l"
{ NEXT_LINE; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 360 "lexer.l"
{ 
			if(return_ret) {
				first_tok = 0;
				return '\n';
			}
			NEXT_LINE;
		}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 367 "lexer.l"
; /*ignore whitespace*/
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 369 "lexer.l"
{
			if(LEX_NOTATION==PREFIX_NOTATION) {
				NO_RET;
			} else {
				DO_RET;
			}
			return yytext[0];
		}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 378 "lexer.l"
{ FUNC_RET; return yytext[0]; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 380 "lexer.l"
{ DO_RET; return '.'; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 382 "lexer.l"
{ NO_RET; return yytext[0]; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 384 "lexer.l"
ECHO;
	YY_BREAK
#line 1290 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(NEGATIVE):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 126 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 126 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 125);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 384 "lexer.l"


void
push_notation(notation_t not)
{
	stack_push(&notation_stack,GINT_TO_POINTER(not));
	if(not==INFIX_NOTATION) {
		BEGIN INITIAL;
	} else {
		BEGIN NEGATIVE;
	}
}

void
pop_notation(void)
{
	notation_t not;
	stack_pop(&notation_stack);

	not = GPOINTER_TO_INT(notation_stack->data);
	if(not==INFIX_NOTATION) {
		BEGIN INITIAL;
	} else {
		BEGIN NEGATIVE;
	}
}

