/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 85
#define YY_END_OF_BUFFER 86
static yyconst short int yy_acclist[361] =
    {   0,
       86,   84,   85,   71,   72,   84,   85,   68,   85,   72,
       84,   85,   72,   84,   85,   80,   84,   85,   84,   85,
       84,   85,   81,   84,   85,   80,   84,   85,   52,   84,
       85,   53,   84,   85,   70,   81,   84,   85,   81,   82,
       84,   85,   66,   81,   84,   85,   66,   81,   84,   85,
       66,   81,   84,   85,   11,   81,   84,   85,   19,   81,
       84,   85,   21,   81,   84,   85,   20,   81,   84,   85,
       81,   84,   85,   54,   81,   84,   85,   50,   81,   84,
       85,   81,   84,   85,   51,   81,   84,   85,   54,   84,
       85,   54,   84,   85,   54,   84,   85,   54,   84,   85,

       54,   84,   85,   54,   84,   85,   54,   84,   85,   54,
       84,   85,   54,   84,   85,   54,   84,   85,   54,   84,
       85,   54,   84,   85,   54,   84,   85,   54,   84,   85,
       54,   84,   85,   54,   84,   85,   54,   84,   85,   54,
       84,   85,   83,   84,   85,   69,   71,   72,   84,   85,
       69,   72,   84,   85,   54,   84,   85,   54,   84,   85,
       54,   84,   85,   54,   84,   85,   71,   72,   68,   72,
       70,   51,   72,   79,   14,   12,    1,   70,   76,   78,
       73,   74,   62,   75,   77,   65,   66,   66,   58,   66,
       66,   17,   15,   13,   18,   48,   54,   50,   67,   54,

       54,   54,   33,   54,   54,   54,   31,   54,   54,   54,
       54,   54,   35,   54,   34,   54,   54,   54,   54,   25,
       54,   54,   54,   54,   54,   54,   32,   54,   54,   54,
       54,   69,   71,   72,   69,   72,   54,   54,   54,   54,
       54,   54,   12,   49,   59,   61,   64,   63,   16,   23,
       54,   54,   54,   54,   54,   54,   54,   28,   54,   54,
       46,   54,   22,   54,   54,   54,   54,   54,   29,   54,
       54,   54,   54,   24,   54,   54,   54,    8,   54,   54,
       60,   57,   54,   54,   40,   54,   54,   37,   54,   54,
       54,   47,   54,   54,   30,   54,   54,   36,   54,   54,

       54,   54,   54,    8,   54,    6,   56,   55,   54,   45,
       54,   54,   54,   54,   54,   54,   27,   54,   26,   54,
        4,   10,    7,   54,   55,   54,   54,   54,   54,   54,
       41,   54,   10,   54,   42,   54,   54,   54,   54,   54,
        9,    3,    3,   44,   54,   54,   38,   54,   54,    2,
        3,   43,   54,   39,   54,    2,    2,    3,    5,    2
    } ;

static yyconst short int yy_accept[281] =
    {   0,
        1,    1,    1,    2,    4,    8,   10,   13,   16,   19,
       21,   23,   26,   29,   32,   35,   39,   43,   47,   51,
       55,   59,   63,   67,   71,   74,   78,   82,   85,   89,
       92,   95,   98,  101,  104,  107,  110,  113,  116,  119,
      122,  125,  128,  131,  134,  137,  140,  143,  146,  151,
      155,  158,  161,  164,  167,  169,  170,  171,  172,  173,
      174,  175,  176,  176,  177,  177,  177,  178,  179,  180,
      181,  182,  182,  183,  184,  185,  186,  186,  188,  189,
      189,  190,  190,  190,  191,  191,  192,  193,  194,  195,
      196,  197,  198,  199,  200,  201,  202,  203,  205,  206,

      207,  209,  210,  211,  212,  213,  215,  217,  218,  219,
      220,  222,  223,  224,  225,  226,  227,  229,  230,  231,
      232,  235,  235,  235,  235,  235,  237,  238,  239,  240,
      241,  242,  243,  244,  245,  245,  246,  246,  247,  248,
      248,  249,  250,  252,  253,  254,  255,  256,  257,  258,
      260,  261,  263,  265,  266,  267,  268,  269,  271,  272,
      273,  274,  276,  276,  276,  276,  276,  276,  276,  276,
      277,  278,  278,  279,  280,  281,  281,  282,  283,  283,
      283,  284,  285,  287,  288,  290,  291,  292,  294,  295,
      297,  298,  300,  301,  302,  302,  302,  302,  302,  302,

      303,  304,  304,  305,  306,  306,  307,  308,  309,  310,
      312,  313,  314,  315,  316,  317,  319,  321,  321,  321,
      321,  321,  322,  322,  323,  323,  323,  324,  325,  326,
      327,  328,  329,  330,  331,  333,  333,  333,  334,  334,
      334,  335,  337,  338,  339,  340,  341,  341,  341,  342,
      342,  343,  343,  344,  344,  344,  344,  346,  347,  349,
      350,  350,  350,  350,  350,  352,  352,  352,  354,  356,
      356,  357,  357,  357,  359,  359,  360,  360,  361,  361
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    1,    9,    1,   10,   11,
       12,   13,   14,   15,   14,   16,   17,   18,   19,   19,
       19,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   22,   27,   28,   28,   28,   28,   29,   28,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       31,   32,   33,   34,   35,   22,   36,   37,   38,   39,

       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,   51,   45,   52,   53,   54,   55,   45,   56,   57,
       58,   45,   59,   60,   12,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[61] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    2,    2,    2,
        2,    1,    1,    1,    1,    1,    1,    2,    2,    3,
        1,    1,    1,    1,    4,    2,    2,    2,    2,    2,
        2,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    1,    1
    } ;

static yyconst short int yy_base[297] =
    {   0,
        0,   59,  536,  537,   63,  537,   67,   71,   56,   56,
      532,  537,  537,  537,  537,   75,  102,  121,  174,   64,
      537,   64,  509,  508,  521,    0,   89,  528,  537,  481,
       43,   57,  479,   51,   37,    0,   64,  478,   59,  475,
       64,  486,  470,   74,  475,  480,  472,  537,  217,  123,
       93,  481,   77,   97,  152,  537,  158,  133,  537,  166,
      537,  537,  119,  537,  140,  517,  537,  171,  537,  537,
      537,  503,  537,  207,  537,  537,  168,  461,  178,  190,
      537,    0,  163,    0,    0,  485,  490,  537,  537,  537,
      537,    0,  172,  537,  476,  470,  473,    0,  465,  462,

        0,  457,  471,  456,  458,    0,    0,  467,  451,  457,
        0,  451,  452,  447,  452,  459,    0,  444,  453,  444,
        0,  456,  454,  152,  119,    0,  210,  446,  456,  228,
      436,  451,  184,  537,  223,  537,  238,  251,    0,  256,
        0,  537,    0,  442,  452,  440,  432,  445,  444,    0,
      445,    0,    0,  435,  445,  441,  424,    0,  429,  433,
      429,    0,  243,  428,  438,  260,  418,  433,  244,  420,
      431,  276,  537,  427,  280,  268,  272,  537,  219,  279,
      418,  421,    0,  360,    0,  352,  348,    0,  352,    0,
      346,    0,  349,  354,  342,  353,  348,  299,  385,  303,

      305,  384,  383,  341,  309,  537,  537,  299,  329,    0,
      333,  327,  336,  337,  320,    0,    0,  319,  321,  321,
      358,  537,  325,  537,  327,  354,  537,  304,  315,  292,
      284,  287,  265,  259,    0,  245,  281,  263,  251,  197,
      335,    0,  213,  202,  175,  177,  336,  177,  537,  156,
      537,  277,  120,  340,  322,  342,    0,   96,    0,   79,
      132,  347,  181,  353,  537,  357,  100,    0,    0,  361,
      537,  365,  369,  235,   96,  537,  373,  347,  537,  405,
      409,  412,   68,  415,  418,  422,  426,  430,  434,  438,
      442,  446,  450,  454,  458,  462

    } ;

static yyconst short int yy_def[297] =
    {   0,
      279,    1,  279,  279,  279,  279,  279,  279,  279,  280,
      281,  279,  279,  279,  279,  279,  279,  279,  279,   19,
      279,  279,  279,  279,  279,  282,  279,  279,  279,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  279,  279,   49,
      282,  282,  282,  282,  279,  279,  279,  279,  279,  279,
      279,  279,  280,  279,  280,  281,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,   18,   18,  279,
      279,  283,  279,   20,  284,   20,  279,  279,  279,  279,
      279,  282,  279,  279,  282,  282,  282,  282,  282,  282,

      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
       49,  279,  279,  279,  279,   50,  282,  282,  282,  282,
      282,  282,  280,  279,  279,  279,  279,  279,  283,  279,
      284,  279,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  279,  279,  279,  279,  279,  279,  285,  282,
      282,  286,  279,  282,  282,  279,  279,  279,  279,  279,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  279,  279,  279,  279,  287,  282,

      282,  288,  288,  282,  279,  279,  279,  279,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  279,  279,  279,
      287,  279,  289,  279,  290,  288,  279,  282,  279,  282,
      282,  282,  282,  282,  282,  279,  291,  291,  292,  293,
      282,  282,  282,  282,  282,  282,  279,  291,  279,  292,
      279,  293,  294,  292,  293,  295,  282,  282,  282,  282,
      294,  279,  294,  292,  279,  293,  296,  282,  282,  279,
      279,  294,  293,  294,  296,  279,  294,  294,    0,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279

    } ;

static yyconst short int yy_nxt[598] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   12,   12,   16,   17,   12,   18,   19,   20,
       20,   12,   21,   22,   23,   24,   25,   26,   26,   26,
       27,   28,   29,   12,   26,   30,   31,   32,   33,   34,
       35,   36,   36,   37,   36,   36,   36,   38,   39,   40,
       41,   42,   43,   44,   45,   46,   47,   36,   14,   48,
       49,   61,   64,   50,   55,   56,   57,   55,   57,  139,
       57,   57,   60,   56,   57,   60,   68,   58,   96,   68,
       62,   86,   86,   86,   86,   58,  104,   65,   87,   88,
       93,  105,   99,   93,   97,   59,   51,  102,  276,  112,

       98,   52,  276,   59,  106,   53,  100,  103,  109,   54,
       69,   70,  107,  110,   71,  113,  116,   72,   73,   74,
       74,   74,   74,  117,  126,   64,  129,  126,   99,  130,
      269,  127,  112,   75,   68,   76,   77,   68,   78,   78,
       78,   79,  100,  131,  268,  262,  133,   80,  113,   80,
       65,  263,  132,   55,   56,   57,   55,  262,  251,   57,
       80,   57,   57,  263,   81,  167,   58,   60,   56,   57,
       60,   65,   68,   93,  168,   68,   93,   82,   83,  249,
       58,  140,  140,  140,   59,   74,   74,   74,   74,   77,
       64,   84,   84,   84,   84,   79,   79,   79,   59,  253,

       80,  165,   80,  137,  166,   85,  272,  138,  138,  138,
      138,  169,  263,   80,  169,   65,  260,   81,  121,   56,
       57,  121,  254,  259,   74,   74,   74,   74,  255,  172,
      173,   58,  172,  135,  279,  135,  176,  208,  208,  208,
      177,  177,  177,  177,  169,  169,  135,  169,  169,   59,
      136,  258,  257,  251,  122,  138,  138,  138,  138,  123,
      262,  172,  173,  124,  172,  249,  263,  125,  138,  138,
      138,  138,  179,  180,  180,  180,  180,  172,  203,  253,
      172,  205,  206,  249,  205,  177,  177,  177,  177,  177,
      177,  177,  177,  247,  178,  179,  180,  180,  180,  180,

      205,  206,  254,  205,  223,  224,  225,  223,  255,  225,
      205,  206,  246,  205,  245,  207,  229,  229,  229,  229,
      223,  224,  225,  223,  253,  225,  223,  238,  225,  223,
      244,  225,  229,  229,  229,  229,  256,  256,  243,  256,
      256,  264,  265,  256,  264,  242,  256,  266,  270,  271,
      240,  270,  241,  255,  264,  265,  227,  264,  273,  274,
      222,  273,  270,  271,  236,  270,  277,  278,  235,  277,
      273,  274,  262,  273,  277,  278,  234,  277,  263,  233,
      232,  231,  254,  230,  228,  227,  227,  222,  255,  220,
      262,  219,  218,  217,  254,  216,  263,  215,  262,  214,

      255,  213,  212,  211,  263,   63,   63,   63,   63,   66,
       66,   66,   66,   92,   92,   92,  141,  141,  199,  199,
      199,  199,  202,  202,  202,  202,  221,  221,  221,  221,
      226,  226,  226,  226,  237,  237,  237,  237,  239,  239,
      239,  239,  248,  248,  248,  248,  250,  250,  250,  250,
      252,  252,  252,  252,  261,  261,  261,  261,  267,  267,
      267,  267,  275,  275,  275,  275,  210,  209,  204,  201,
      200,  198,  197,  196,  195,  194,  193,  192,  191,  190,
      189,  188,  187,  186,  185,  184,  183,  182,  181,  175,
      174,  171,  170,  164,  163,  162,  161,  160,  159,  158,

      157,  156,  155,  154,  153,  152,  151,  150,  149,  148,
      147,  146,  145,  144,  143,  142,  279,  279,  134,   67,
      128,  120,  119,  118,  115,  114,  111,  108,  101,   95,
       94,   91,   90,   89,   67,  279,    3,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279

    } ;

static yyconst short int yy_chk[598] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        2,    9,   10,    2,    5,    5,    5,    5,    7,  283,
        7,    7,    8,    8,    8,    8,   16,    5,   31,   16,
        9,   20,   20,   20,   20,    8,   35,   10,   22,   22,
       27,   35,   32,   27,   31,    5,    2,   34,  275,   41,

       31,    2,  267,    8,   37,    2,   32,   34,   39,    2,
       17,   17,   37,   39,   17,   41,   44,   17,   17,   17,
       17,   17,   17,   44,   50,   63,   53,   50,   51,   53,
      260,   51,   54,   17,   58,   17,   18,   58,   18,   18,
       18,   18,   51,   54,  258,  253,   65,   18,   54,   18,
       63,  253,   54,   55,   55,   55,   55,  261,  250,   57,
       18,   57,   57,  261,   18,  125,   55,   60,   60,   60,
       60,   65,   68,   93,  125,   68,   93,   18,   19,  248,
       60,   83,   83,   83,   55,   77,   77,   77,   77,   19,
      133,   19,   19,   19,   19,   79,   79,   79,   60,  240,

       19,  124,   19,   80,  124,   19,  263,   80,   80,   80,
       80,  127,  263,   19,  127,  133,  246,   19,   49,   49,
       49,   49,  240,  245,   74,   74,   74,   74,  240,  130,
      130,   49,  130,   74,   79,   74,  135,  179,  179,  179,
      135,  135,  135,  135,  163,  169,   74,  163,  169,   49,
       74,  244,  243,  239,   49,  137,  137,  137,  137,   49,
      274,  166,  166,   49,  166,  238,  274,   49,  138,  138,
      138,  138,  140,  140,  140,  140,  140,  172,  172,  252,
      172,  175,  175,  237,  175,  176,  176,  176,  176,  177,
      177,  177,  177,  236,  138,  180,  180,  180,  180,  180,

      198,  198,  252,  198,  200,  200,  201,  200,  252,  201,
      205,  205,  234,  205,  233,  177,  208,  208,  208,  208,
      218,  218,  219,  218,  255,  219,  223,  223,  225,  223,
      232,  225,  229,  229,  229,  229,  241,  247,  231,  241,
      247,  254,  254,  256,  254,  230,  256,  255,  262,  262,
      225,  262,  228,  255,  264,  264,  226,  264,  266,  266,
      221,  266,  270,  270,  220,  270,  272,  272,  215,  272,
      273,  273,  278,  273,  277,  277,  214,  277,  278,  213,
      212,  211,  266,  209,  204,  203,  202,  199,  266,  197,
      272,  196,  195,  194,  273,  193,  272,  191,  277,  189,

      273,  187,  186,  184,  277,  280,  280,  280,  280,  281,
      281,  281,  281,  282,  282,  282,  284,  284,  285,  285,
      285,  285,  286,  286,  286,  286,  287,  287,  287,  287,
      288,  288,  288,  288,  289,  289,  289,  289,  290,  290,
      290,  290,  291,  291,  291,  291,  292,  292,  292,  292,
      293,  293,  293,  293,  294,  294,  294,  294,  295,  295,
      295,  295,  296,  296,  296,  296,  182,  181,  174,  171,
      170,  168,  167,  165,  164,  161,  160,  159,  157,  156,
      155,  154,  151,  149,  148,  147,  146,  145,  144,  132,
      131,  129,  128,  123,  122,  120,  119,  118,  116,  115,

      114,  113,  112,  110,  109,  108,  105,  104,  103,  102,
      100,   99,   97,   96,   95,   87,   86,   78,   72,   66,
       52,   47,   46,   45,   43,   42,   40,   38,   33,   30,
       28,   25,   24,   23,   11,    3,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279

    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#define INITIAL 0
/* GENIUS Calculator
 * Copyright (C) 1997-2002 George Lebl
 *
 * Author: George Lebl
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the  Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307,
 * USA.
 */
#line 22 "lexer.l"
#include "config.h"

#include <glib.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include "mpwrap.h"
#include "eval.h"
#include "dict.h"
#include "calc.h"
#include "parse.h"
#include "util.h"

int lex_fd[2];
int first_tok = STARTTOK;
int return_ret = FALSE;
int parenth_depth = 0;
int lex_init = TRUE;
extern GSList *evalstack;
extern int got_eof;
static int matrix_entry = 0;
static GSList *matrix_entry_stack = NULL;


#define NO_RET {return_ret = FALSE;}
#define DO_RET { \
	if(!parenth_depth) \
		return_ret = TRUE; \
	else \
		return_ret = FALSE; \
}

static GHashTable *fp_hash = NULL;

void my_yy_open(FILE *fp);
void my_yy_parse(FILE *fp);
void my_yy_close(FILE *fp);

void
my_yy_open(FILE *fp)
{
	YY_BUFFER_STATE buf;
	if(!fp_hash)
		fp_hash = g_hash_table_new(NULL, NULL);

	buf = g_hash_table_lookup(fp_hash, fp);
	if(buf)
		return;

	buf = yy_create_buffer(fp, YY_BUF_SIZE);
	g_hash_table_insert(fp_hash, fp, buf);
}

void
my_yy_parse(FILE *fp)
{
	YY_BUFFER_STATE buf;

	g_assert(fp_hash);

	buf = g_hash_table_lookup(fp_hash, fp);

	yy_switch_to_buffer(buf);
	yyparse();
}

void
my_yy_close(FILE *fp)
{
	YY_BUFFER_STATE buf;

	/* don't close the stdin */
	if(fp == stdin)
		return;

	g_assert(fp_hash);

	buf = g_hash_table_lookup(fp_hash, fp);

	yy_delete_buffer(buf);

	 g_hash_table_remove(fp_hash, fp);
}

#line 745 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 109 "lexer.l"



	if(lex_init) {
		return_ret = FALSE;
		parenth_depth = 0;
		matrix_entry = 0;
		matrix_entry_stack = NULL;
		lex_init = FALSE;
	}
	
	if(first_tok!=INT_MAX) {
		int i = first_tok;
		first_tok = INT_MAX;
		return i;
	}



#line 919 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 280 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 537 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 128 "lexer.l"
; /*comment, ignore*/
	YY_BREAK
case 2:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 130 "lexer.l"
{
			char *s;
			char *end;
			if(evalstack || parenth_depth) {REJECT;}
			s=strchr(yytext,'<')+1; /*find the beginning*/
			end=strrchr(yytext,'>'); /*find the end*/
			s = unescape_string(s,end,NULL);
			yylval.id = g_strconcat(LIBRARY_DIR,"/",s,NULL);
			g_free(s);
			DO_RET;
			return LOADFILE;
		}
	YY_BREAK
case 3:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 143 "lexer.l"
{
			char *s;
			if(evalstack || parenth_depth) {REJECT;}
			s=strchr(yytext,'d')+1; /*move after the load*/
			/*btw from the above RE we know this will work*/
			while(*s==' ' || *s=='\t')
				s++;
			yylval.id = g_strdup(s);
			DO_RET;
			return LOADFILE_GLOB;
		}
	YY_BREAK
case 4:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 155 "lexer.l"
{
			char *s;
			if(evalstack || parenth_depth) {REJECT;}
			s=strchr(yytext,'d')+1; /*move after the cd*/
			/*btw from the above RE we know this will work*/
			while(*s==' ' || *s=='\t')
				s++;
			yylval.id = g_strdup(s);
			DO_RET;
			return CHANGEDIR;
		}
	YY_BREAK
case 5:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 167 "lexer.l"
{
			char *s;
			if(evalstack || parenth_depth) {REJECT;}
			s=strchr(yytext,'n')+1; /*move after the plugin*/
			/*btw from the above RE we know this will work*/
			while(*s==' ' || *s=='\t')
				s++;
			yylval.id = g_strdup(s);
			DO_RET;
			return LOAD_PLUGIN;
		}
	YY_BREAK
case 6:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 179 "lexer.l"
{
			if(evalstack || parenth_depth) {REJECT;}
			DO_RET;
			return PWD;
		}
	YY_BREAK
case 7:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 185 "lexer.l"
{
			char *s;
			if(evalstack || parenth_depth) {REJECT;}
			s=strchr(yytext,'s')+1; /*move after the ls*/
			/*btw from the above RE we know this will work*/
			while(*s==' ' || *s=='\t')
				s++;
			yylval.id = g_strdup(s);
			DO_RET;
			return LS_ARG;
		}
	YY_BREAK
case 8:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 197 "lexer.l"
{
			if(evalstack || parenth_depth) {REJECT;}
			DO_RET;
			return LS;
		}
	YY_BREAK
case 9:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 203 "lexer.l"
{
			char *s;
			if(evalstack || parenth_depth) {REJECT;}
			s=strchr(yytext,'p')+1; /*move after the help*/
			/*btw from the above RE we know this will work*/
			while(*s==' ' || *s=='\t')
				s++;
			yylval.id = g_strdup(s);
			DO_RET;
			return HELP_ARG;
		}
	YY_BREAK
case 10:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 215 "lexer.l"
{
			if(evalstack || parenth_depth) {REJECT;}
			DO_RET;
			return HELP;
		}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 222 "lexer.l"
{
			if (matrix_entry &&
			    GPOINTER_TO_INT(matrix_entry_stack->data) == 0) {
				return NEXTROW;
			}
			DO_RET;
			return SEPAR;
		}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 231 "lexer.l"
{ 
			DO_RET;
			yylval.id = unescape_string(&yytext[1],NULL,NULL);
			/*kill the trailing "*/
			yylval.id[strlen(yylval.id)-1]='\0';
			return STRING;
		}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 239 "lexer.l"
{ NO_RET; return EQ_CMP; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 240 "lexer.l"
{ NO_RET; return NE_CMP; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 241 "lexer.l"
{ NO_RET; return NE_CMP; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 242 "lexer.l"
{ NO_RET; return CMP_CMP; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 244 "lexer.l"
{ NO_RET; return LE_CMP; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 245 "lexer.l"
{ NO_RET; return GE_CMP; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 247 "lexer.l"
{ NO_RET; return LT_CMP; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 248 "lexer.l"
{ NO_RET; return GT_CMP; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 250 "lexer.l"
{ NO_RET; return EQUALS; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 252 "lexer.l"
{ NO_RET; return LOGICAL_NOT; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 253 "lexer.l"
{ NO_RET; return LOGICAL_AND; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 254 "lexer.l"
{ NO_RET; return LOGICAL_XOR; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 255 "lexer.l"
{ NO_RET; return LOGICAL_OR; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 257 "lexer.l"
{ NO_RET; return WHILE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 258 "lexer.l"
{ NO_RET; return UNTIL; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 259 "lexer.l"
{ NO_RET; return FOR; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 260 "lexer.l"
{ NO_RET; return SUM; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 261 "lexer.l"
{ NO_RET; return PROD; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 262 "lexer.l"
{ NO_RET; return DO; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 263 "lexer.l"
{ NO_RET; return TO; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 264 "lexer.l"
{ NO_RET; return BY; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 265 "lexer.l"
{ NO_RET; return IN; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 266 "lexer.l"
{ NO_RET; return IF; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 267 "lexer.l"
{ NO_RET; return THEN; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 268 "lexer.l"
{ NO_RET; return ELSE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 270 "lexer.l"
{ NO_RET; return FUNCTION; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 271 "lexer.l"
{ NO_RET; return PARAMETER; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 272 "lexer.l"
{ NO_RET; return CALL; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 274 "lexer.l"
{ NO_RET; return RETURNTOK; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 275 "lexer.l"
{ DO_RET; return BAILOUT; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 276 "lexer.l"
{ DO_RET; return EXCEPTION; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 277 "lexer.l"
{ DO_RET; return CONTINUE; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 278 "lexer.l"
{ DO_RET; return BREAK; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 280 "lexer.l"
{ NO_RET; return MOD; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 282 "lexer.l"
{ DO_RET; return '.'; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 284 "lexer.l"
{
			parenth_depth++;
			if (matrix_entry_stack != NULL)
				matrix_entry_stack->data =
					GINT_TO_POINTER
					  (GPOINTER_TO_INT(matrix_entry_stack->data) + 1);
			NO_RET;
			return AT;
		}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 293 "lexer.l"
{
			NO_RET;
			return THREEDOTS;
		}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 298 "lexer.l"
{
			matrix_entry++;
			parenth_depth++;
			matrix_entry_stack =
				g_slist_prepend (matrix_entry_stack,
						 GINT_TO_POINTER (0));
			NO_RET;
			return '[';
		}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 308 "lexer.l"
{
			GSList *li;
			matrix_entry--;
			parenth_depth--;
			li = matrix_entry_stack;
			matrix_entry_stack = g_slist_remove_link (matrix_entry_stack, li);
			g_slist_free_1 (li);
			DO_RET;
			return ']';
		}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 320 "lexer.l"
{
			parenth_depth++;
			if (matrix_entry_stack != NULL)
				matrix_entry_stack->data =
					GINT_TO_POINTER
					  (GPOINTER_TO_INT(matrix_entry_stack->data) + 1);
			NO_RET;
			return yytext[0];
		}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 330 "lexer.l"
{
			parenth_depth--;
			if (matrix_entry_stack != NULL)
				matrix_entry_stack->data =
					GINT_TO_POINTER
					  (GPOINTER_TO_INT(matrix_entry_stack->data) - 1);
			DO_RET;
			return yytext[0];
		}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 340 "lexer.l"
{
				/* identifier*/
				yylval.id = g_strdup(yytext);
				DO_RET;
				return FUNCID;
			}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 347 "lexer.l"
{
			mpw_init(yylval.val);
			mpw_set_str(yylval.val,yytext,10);
			DO_RET;
			return NUMBER;
		}
	YY_BREAK
case 56:
#line 355 "lexer.l"
case 57:
#line 356 "lexer.l"
case 58:
#line 357 "lexer.l"
case 59:
YY_RULE_SETUP
#line 357 "lexer.l"
{
			char *s;
			if(yytext[0] == '.')
				s = g_strconcat("0",&yytext[0],NULL);
			else
				s = g_strdup(yytext);
			mpw_init(yylval.val);
			mpw_set_str_complex(yylval.val,s,10);
			g_free(s);
			DO_RET;
			return NUMBER;
		}
	YY_BREAK
case 60:
#line 372 "lexer.l"
case 61:
#line 373 "lexer.l"
case 62:
YY_RULE_SETUP
#line 373 "lexer.l"
{
			char *s;
			if(yytext[0] == '.')
				s = g_strconcat("0",&yytext[0],NULL);
			else
				s = g_strdup(yytext);
			mpw_init(yylval.val);
			mpw_set_str_float(yylval.val,s,10);
			g_free(s);
			DO_RET;
			return NUMBER;
		}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 387 "lexer.l"
{
			char *s;
			int base;

			s=g_malloc(strlen(yytext)-2); /*minus 3 and plus 1*/
			sscanf(yytext,"%d\\%[0-9a-zA-Z]s",&base,s);
			if(base>36) { g_free(s); REJECT; }
			mpw_init(yylval.val);
			mpw_set_str_int(yylval.val,s,base);
			g_free(s);
			DO_RET;
			return NUMBER;
		}
	YY_BREAK
case 64:
#line 402 "lexer.l"
case 65:
#line 403 "lexer.l"
case 66:
YY_RULE_SETUP
#line 403 "lexer.l"
{
			mpw_init(yylval.val);
			mpw_set_str_int(yylval.val,yytext,0);
			DO_RET;
			return NUMBER;
		}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 410 "lexer.l"
{ incr_file_info(); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 412 "lexer.l"
{ 
			incr_file_info();
			if(matrix_entry) {
				return NEXTROW;
			} else if(return_ret) {
				first_tok = 0;
				return '\n';
			}
		}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 422 "lexer.l"
;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 424 "lexer.l"
{ return ','; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 426 "lexer.l"
{
			if(matrix_entry)
				return ',';
		}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 431 "lexer.l"
; /*ignore whitespace*/
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 433 "lexer.l"
{ DO_RET; return ELTELTMUL; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 434 "lexer.l"
{ DO_RET; return ELTELTDIV; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 435 "lexer.l"
{ DO_RET; return ELTELTBACKDIV; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 436 "lexer.l"
{ DO_RET; return ELTELTMOD; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 437 "lexer.l"
{ DO_RET; return ELTELTEXP; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 438 "lexer.l"
{ DO_RET; return TRANSPOSE; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 440 "lexer.l"
{ DO_RET; return DOUBLEFACT; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 442 "lexer.l"
{
			DO_RET;
			return yytext[0];
		}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 447 "lexer.l"
{ NO_RET; return yytext[0]; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 449 "lexer.l"
{ DO_RET; return '.'; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 451 "lexer.l"
{ DO_RET; return '|'; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 453 "lexer.l"
{
			got_eof = TRUE;
			return '\n';
		}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 458 "lexer.l"
{ NO_RET; return yytext[0]; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 460 "lexer.l"
ECHO;
	YY_BREAK
#line 1638 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 280 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 280 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 279);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 460 "lexer.l"


int my_yyinput(void);
int my_yyinput(void) { return input(); }
